# yaml-language-server: $schema=https://apps.kelvininc.com/schemas/kelvin/4.12.0/app/app.json
app:
  kelvin:
    configuration: {}
    inputs:
      - data_type: number
        name: stage_first_suction_p
      - data_type: number
        name: stage_first_discharge_p
      - data_type: number
        name: stage_second_suction_p
      - data_type: number
        name: stage_first_suction_temp
      - data_type: number
        name: suction_flow
      - data_type: number
        name: discharge_flow
      - data_type: number
        name: primary_seal_gas_p
      - data_type: number
        name: secondary_seal_gas_p_de
      - data_type: number
        name: secondary_seal_gas_p_nde
      - data_type: number
        name: primary_seal_vent_flow_de
      - data_type: number
        name: primary_seal_vent_flow_nde
      - data_type: number
        name: primary_seal_supply_dp
      - data_type: number
        name: lube_oil_header_pressure
      - data_type: number
        name: compressor_journal_bearing_temperature_de
      - data_type: number
        name: compressor_journal_bearing_temp_nde
      - data_type: number
        name: ratio
      - data_type: number
        name: stage_first_discharge_temperature
      - data_type: number
        name: turbine_inlet_vibrations
      - data_type: number
        name: steam_turbine_inlet_steam_temp
      - data_type: number
        name: steam_turbine_inlet_steam_flow
      - data_type: number
        name: steam_turbine_inlet_steam_pressure
      - data_type: number
        name: steam_turbine_outlet_pressure
      - data_type: number
        name: steam_turbine_outlet_steam_temp
      - data_type: number
        name: power
      - data_type: number
        name: stage_first_polytropic_efficiency
      - data_type: number
        name: turbine_axial_displacement_b
      - data_type: number
        name: turbine_axial_displacement_a
      - data_type: number
        name: compressor_speed

    outputs:
      - data_type: number
        name: compressor_speed
        control_change: true

    language:
      python:
        entry_point: kelvin_python_sdk
      type: python

    parameters: []
  type: kelvin
info:
  description: compressor-anomaly-detection
  name: compressor-anomaly-detection
  title: compressor-anomaly-detection
  version: 2.0.0
spec_version: 4.12.0
system:
  environment_vars:
    - name: KELVIN_GW_MODE
      value: SOCKETS
